---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nwdb-pvc #volumn name
  labels:
    app: northwind
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage


