---
#create a namespace
apiVersion: v1 # if it's core, just v1, if the group of the api is app, need to write app/v1
kind: Namespace
metadata: 
  name: myns # name of the namespace
  labels: #any key value pair
    dept: engineering
    app: fortune
---
#create a port
apiVersion: v1
kind: Pod
metadata:
  name: fortune-pod
  namespace: myns
  labels:
    name: fortune-pod
    dept: engineering
    app: fortune
spec:
  containers:
  - name: fortune-constainer
    image: xiong1216/fortune:v3
    imagePullPolicy: IfNotPresent
    env: 
    - name: APP_PORT
      value: "8080" #VALUE HAS TO BE STRING
    ports:
    - name: fortune-port 
      containerPort: 8080 # port
