---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-cluster-secret
  labels:
    app: wordpress
data:
  ROOT_PASSWORD: Y2hhbmdlaXQ=

---
# create a cluster using CRD (custom resource definition)
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 2 # one master one slave
  secretName: wordpress-cluster-secret
  persistentVolumeClaim: 
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
    storageClassName: do-block-storage

